-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["player"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30.5, -4.5  ,  -25.5, -0.5  ,  -26.5, 5.5  ,  -31.5, 8.5  ,  -42.5, -4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20.5, 24.5  ,  -15.5, 26.5  ,  -20.5, 28.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27.5, 17.5  ,  -20.5, 24.5  ,  -29.5, 22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 15.5  ,  22.5, 16.5  ,  41.5, 0.5  ,  45.5, 7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1.5, -14.5  ,  9.5, -23.5  ,  16.5, -28.5  ,  28.5, -28.5  ,  30.5, -25.5  ,  17.5, -12.5  ,  5.5, -7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40.5, -20.5  ,  30.5, -25.5  ,  43.5, -25.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   41.5, 0.5  ,  40.5, -20.5  ,  46.5, -13.5  ,  47.5, -4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26.5, 5.5  ,  -13.5, 7.5  ,  -27.5, 17.5  ,  -30.5, 17.5  ,  -31.5, 8.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   22.5, 16.5  ,  9.5, 24.5  ,  11.5, -2.5  ,  17.5, -12.5  ,  30.5, -25.5  ,  40.5, -20.5  ,  41.5, 0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29.5, -20.5  ,  -31.5, -10.5  ,  -45.5, -16.5  ,  -43.5, -22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9.5, 24.5  ,  22.5, 16.5  ,  7.5, 39.5  ,  1.5, 39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9.5, -39.5  ,  16.5, -28.5  ,  9.5, -23.5  ,  5.5, -28.5  ,  5.5, -39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9.5, -23.5  ,  -1.5, -14.5  ,  -0.5, -19.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5.5, 5.5  ,  7.5, 22.5  ,  -13.5, 7.5  ,  -31.5, -10.5  ,  -29.5, -20.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27.5, 17.5  ,  -13.5, 7.5  ,  7.5, 22.5  ,  -15.5, 26.5  ,  -20.5, 24.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9.5, 24.5  ,  7.5, 22.5  ,  -5.5, 5.5  ,  11.5, -2.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "mouth", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, 26.5  ,  7.5, 22.5  ,  -16.5, 29.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "eat", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6.5, 6.5  ,  -28.5, -19.5  ,  -0.5, -13.5  ,  10.5, -1.5  }
                    }
                    
                    
                    
		}
		
		, 
		["tablecloth"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "tablecloth", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  188, 87  ,  241, 62  }
                    }
                     ,
                    {
                    pe_fixture_id = "tablecloth", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  134, 108  ,  188, 87  }
                    }
                     ,
                    {
                    pe_fixture_id = "tablecloth", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  28, 138  ,  134, 108  }
                    }
                     ,
                    {
                    pe_fixture_id = "tablecloth", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   -79, 152  ,  -241, 160  ,  -241, 147  }
                    }
                     ,
                    {
                    pe_fixture_id = "tablecloth", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  -79, 152  ,  28, 138  }
                    }
                     ,
                    {
                    pe_fixture_id = "tablecloth", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  -241, 160  ,  -79, 152  }
                    }
                    
                    
                    
		}
		
		, 
		["CHICKEN"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   17.5, -15  ,  10.5, -14  ,  14.5, -24  ,  19.5, -25  ,  24.5, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32.5, -14  ,  28.5, -13  ,  26.5, -21  ,  31.5, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21.5, -10  ,  25.5, 2  ,  16.5, 13  ,  10.5, -14  ,  17.5, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28.5, -13  ,  25.5, 2  ,  21.5, -10  ,  26.5, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16.5, 13  ,  1.5, 25  ,  -16.5, 25  ,  -27.5, 23  ,  -32.5, 9  ,  -29.5, -2  ,  -19.5, -12  ,  10.5, -14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1.5, 25  ,  16.5, 13  ,  19.5, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, 9  ,  -27.5, 23  ,  -31.5, 19  }
                    }
                    
                    
                    
		}
		
		, 
		["CRAB"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, 11.5  ,  11, 11.5  ,  -3, -16.5  ,  0, -17.5  ,  8, -13.5  ,  17, -5.5  ,  25, 5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2, 14.5  ,  11, 11.5  ,  13, 11.5  ,  9, 18.5  ,  -1, 20.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   17, -5.5  ,  8, -13.5  ,  11, -16.5  ,  21, -15.5  ,  23, -8.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, 9.5  ,  -20, -0.5  ,  -14, -5.5  ,  -14, 17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3, -20.5  ,  -3, -16.5  ,  -13, -12.5  ,  -14, -18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, -5.5  ,  -13, -12.5  ,  -3, -16.5  ,  11, 11.5  ,  -7, 8.5  ,  -14, 2.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, -10.5  ,  -19, -7.5  ,  -25, 2.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, -12.5  ,  -14, -5.5  ,  -19, -7.5  ,  -22, -10.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, -17.5  ,  -3, -16.5  ,  2, -19.5  }
                    }
                    
                    
                    
		}
		
		, 
		["FISH"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, 3.5  ,  11, -5.5  ,  21, -4.5  ,  30, 4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, -4.5  ,  11, -5.5  ,  21, -12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, -5.5  ,  11, -5.5  ,  11, 3.5  ,  -4, 12.5  ,  -25, 12.5  ,  -30, 9.5  ,  -26, -1.5  }
                    }
                    
                    
                    
		}
		
		, 
		["MEAT"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37, -12  ,  -20, -20  ,  11, -20  ,  15, -13  ,  -23, 9  ,  -37, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 18  ,  -20, 20  ,  -23, 9  ,  15, -13  ,  37, -2  }
                    }
                    
                    
                    
		}
		
		, 
		["Cake"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8.5, 26  ,  -27.5, 11  ,  -27.5, -16  ,  -7.5, -22  ,  19.5, -17  ,  27.5, -4  ,  27.5, 27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4.5, -28  ,  19.5, -17  ,  -7.5, -22  ,  -4.5, -28  }
                    }
                    
                    
                    
		}
		
		, 
		["Dabeli"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27.5, 11.5  ,  17.5, 18.5  ,  -7.5, 20.5  ,  -20.5, 16.5  ,  -26.5, 10.5  ,  -14.5, -20.5  ,  8.5, -20.5  ,  27.5, -10.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14.5, -20.5  ,  -26.5, 10.5  ,  -27.5, -11.5  }
                    }
                    
                    
                    
		}
		
		, 
		["DONUT"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, -11.5  ,  -9, -15.5  ,  20, -15.5  ,  30, 1.5  ,  6, 14.5  ,  -22, 15.5  ,  -29, 10.5  ,  -30, -3.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, 1.5  ,  20, -15.5  ,  29, -8.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 14.5  ,  30, 1.5  ,  25, 8.5  }
                    }
                    
                    
                    
		}
		
		, 
		["DOSA"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   19.5, 10  ,  4.5, 10  ,  -30.5, 0  ,  -32.5, -8  ,  -14.5, -10  ,  26.5, -5  ,  32.5, 3  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

