-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:9d080a011b47e90901697e1c3ef87ce6$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "game abhijit_010001.png",
				spriteColorRect = { x = 242, y = 226, width = 266, height = 226 },
				textureRect = { x = 2, y = 2, width = 266, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010002.png",
				spriteColorRect = { x = 234, y = 228, width = 274, height = 224 },
				textureRect = { x = 270, y = 2, width = 274, height = 224 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010003.png",
				spriteColorRect = { x = 234, y = 230, width = 274, height = 222 },
				textureRect = { x = 546, y = 2, width = 274, height = 222 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010004.png",
				spriteColorRect = { x = 234, y = 230, width = 274, height = 222 },
				textureRect = { x = 2, y = 230, width = 274, height = 222 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010005.png",
				spriteColorRect = { x = 242, y = 232, width = 266, height = 220 },
				textureRect = { x = 278, y = 230, width = 266, height = 220 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010006.png",
				spriteColorRect = { x = 242, y = 232, width = 266, height = 220 },
				textureRect = { x = 278, y = 230, width = 266, height = 220 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010007.png",
				spriteColorRect = { x = 234, y = 230, width = 274, height = 222 },
				textureRect = { x = 546, y = 230, width = 274, height = 222 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010008.png",
				spriteColorRect = { x = 234, y = 230, width = 274, height = 222 },
				textureRect = { x = 546, y = 2, width = 274, height = 222 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010009.png",
				spriteColorRect = { x = 234, y = 228, width = 274, height = 224 },
				textureRect = { x = 2, y = 454, width = 274, height = 224 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010010.png",
				spriteColorRect = { x = 242, y = 226, width = 266, height = 226 },
				textureRect = { x = 2, y = 2, width = 266, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010011.png",
				spriteColorRect = { x = 286, y = 232, width = 216, height = 220 },
				textureRect = { x = 278, y = 454, width = 216, height = 220 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010012.png",
				spriteColorRect = { x = 296, y = 230, width = 210, height = 222 },
				textureRect = { x = 496, y = 454, width = 210, height = 222 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010013.png",
				spriteColorRect = { x = 307, y = 226, width = 200, height = 226 },
				textureRect = { x = 708, y = 454, width = 200, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010014.png",
				spriteColorRect = { x = 307, y = 226, width = 200, height = 226 },
				textureRect = { x = 2, y = 682, width = 200, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010015.png",
				spriteColorRect = { x = 307, y = 226, width = 200, height = 226 },
				textureRect = { x = 204, y = 682, width = 200, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010016.png",
				spriteColorRect = { x = 307, y = 226, width = 200, height = 226 },
				textureRect = { x = 406, y = 682, width = 200, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010017.png",
				spriteColorRect = { x = 307, y = 226, width = 200, height = 226 },
				textureRect = { x = 608, y = 682, width = 200, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010018.png",
				spriteColorRect = { x = 307, y = 226, width = 200, height = 226 },
				textureRect = { x = 810, y = 682, width = 200, height = 226 },
				spriteSourceSize = { width = 788, height = 452 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

