-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:57384e251f285c12e31cf36e21387cf7$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "12.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 2, y = 2, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "13.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 32 },
				textureRect = { x = 54, y = 2, width = 75, height = 32 },
				spriteSourceSize = { width = 75, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "14.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 37 },
				textureRect = { x = 131, y = 2, width = 50, height = 37 },
				spriteSourceSize = { width = 50, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "game abhijit_010001.png",
				spriteColorRect = { x = 406, y = 378, width = 406, height = 342 },
				textureRect = { x = 183, y = 2, width = 406, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010002.png",
				spriteColorRect = { x = 392, y = 380, width = 420, height = 340 },
				textureRect = { x = 591, y = 2, width = 420, height = 340 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010003.png",
				spriteColorRect = { x = 392, y = 384, width = 420, height = 336 },
				textureRect = { x = 1013, y = 2, width = 420, height = 336 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010004.png",
				spriteColorRect = { x = 392, y = 386, width = 420, height = 334 },
				textureRect = { x = 1435, y = 2, width = 420, height = 334 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010005.png",
				spriteColorRect = { x = 406, y = 388, width = 406, height = 332 },
				textureRect = { x = 2, y = 346, width = 406, height = 332 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010006.png",
				spriteColorRect = { x = 406, y = 388, width = 406, height = 332 },
				textureRect = { x = 2, y = 346, width = 406, height = 332 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010007.png",
				spriteColorRect = { x = 392, y = 386, width = 420, height = 334 },
				textureRect = { x = 410, y = 346, width = 420, height = 334 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010008.png",
				spriteColorRect = { x = 392, y = 384, width = 420, height = 336 },
				textureRect = { x = 1013, y = 2, width = 420, height = 336 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010009.png",
				spriteColorRect = { x = 392, y = 380, width = 420, height = 340 },
				textureRect = { x = 832, y = 346, width = 420, height = 340 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010010.png",
				spriteColorRect = { x = 406, y = 378, width = 406, height = 342 },
				textureRect = { x = 183, y = 2, width = 406, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010011.png",
				spriteColorRect = { x = 477, y = 388, width = 326, height = 332 },
				textureRect = { x = 1254, y = 346, width = 326, height = 332 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010012.png",
				spriteColorRect = { x = 495, y = 384, width = 314, height = 336 },
				textureRect = { x = 1582, y = 346, width = 314, height = 336 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010013.png",
				spriteColorRect = { x = 514, y = 378, width = 296, height = 342 },
				textureRect = { x = 2, y = 688, width = 296, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010014.png",
				spriteColorRect = { x = 514, y = 378, width = 296, height = 342 },
				textureRect = { x = 300, y = 688, width = 296, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010015.png",
				spriteColorRect = { x = 514, y = 378, width = 296, height = 342 },
				textureRect = { x = 598, y = 688, width = 296, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010016.png",
				spriteColorRect = { x = 514, y = 378, width = 296, height = 342 },
				textureRect = { x = 896, y = 688, width = 296, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010017.png",
				spriteColorRect = { x = 514, y = 378, width = 296, height = 342 },
				textureRect = { x = 1194, y = 688, width = 296, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "game abhijit_010018.png",
				spriteColorRect = { x = 514, y = 378, width = 296, height = 342 },
				textureRect = { x = 1492, y = 688, width = 296, height = 342 },
				spriteSourceSize = { width = 1280, height = 720 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

