-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:4b13802bb247b8fdaacfab77b2cca41d$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "10001.png",
				spriteColorRect = { x = 2, y = 0, width = 98, height = 93 },
				textureRect = { x = 2, y = 2, width = 98, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10002.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 93 },
				textureRect = { x = 102, y = 2, width = 100, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10003.png",
				spriteColorRect = { x = 0, y = 1, width = 100, height = 93 },
				textureRect = { x = 204, y = 2, width = 100, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10004.png",
				spriteColorRect = { x = 0, y = 2, width = 100, height = 93 },
				textureRect = { x = 306, y = 2, width = 100, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10005.png",
				spriteColorRect = { x = 2, y = 2, width = 98, height = 93 },
				textureRect = { x = 408, y = 2, width = 98, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10006.png",
				spriteColorRect = { x = 2, y = 2, width = 98, height = 93 },
				textureRect = { x = 408, y = 2, width = 98, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10007.png",
				spriteColorRect = { x = 0, y = 2, width = 100, height = 93 },
				textureRect = { x = 2, y = 97, width = 100, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10008.png",
				spriteColorRect = { x = 0, y = 1, width = 100, height = 93 },
				textureRect = { x = 204, y = 2, width = 100, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10009.png",
				spriteColorRect = { x = 0, y = 1, width = 100, height = 93 },
				textureRect = { x = 306, y = 2, width = 100, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10010.png",
				spriteColorRect = { x = 2, y = 0, width = 98, height = 93 },
				textureRect = { x = 2, y = 2, width = 98, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10011.png",
				spriteColorRect = { x = 20, y = 2, width = 78, height = 91 },
				textureRect = { x = 104, y = 97, width = 78, height = 91 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10012.png",
				spriteColorRect = { x = 24, y = 0, width = 76, height = 93 },
				textureRect = { x = 184, y = 97, width = 76, height = 93 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10013.png",
				spriteColorRect = { x = 28, y = 0, width = 72, height = 95 },
				textureRect = { x = 262, y = 97, width = 72, height = 95 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10014.png",
				spriteColorRect = { x = 28, y = 0, width = 72, height = 95 },
				textureRect = { x = 336, y = 97, width = 72, height = 95 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10015.png",
				spriteColorRect = { x = 28, y = 0, width = 72, height = 95 },
				textureRect = { x = 410, y = 97, width = 72, height = 95 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10016.png",
				spriteColorRect = { x = 28, y = 0, width = 72, height = 95 },
				textureRect = { x = 2, y = 194, width = 72, height = 95 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10017.png",
				spriteColorRect = { x = 28, y = 0, width = 72, height = 95 },
				textureRect = { x = 76, y = 194, width = 72, height = 95 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "10018.png",
				spriteColorRect = { x = 28, y = 0, width = 72, height = 95 },
				textureRect = { x = 150, y = 194, width = 72, height = 95 },
				spriteSourceSize = { width = 100, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

